	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/js/popper.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/js/jquery.magnific-popup.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/js/jquery.nice-select.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/js/jquery.form.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/global/jquery-validation/dist/jquery.validate.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/js/custom.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/promadel/datatables/datatables.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/pace/pace.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/global/sweetalert/sweetalert2.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/global/alphanum/jquery.alphanum.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/global/CKEditor5/ckeditor.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/toastr/toastr.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/select2/dist/js/select2.full.min.js"></script>