	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bootstrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/dist-portal/js/adminlte.min.js"></script>
	<!-- DATATABLE -->
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-datatables/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-datatables/js/dataTables.bootstrap.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-datatables/js/dataTables.responsive.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-datatables/js/buttons/dataTables.buttons.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-datatables/js/buttons/buttons.html5.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-datatables/js/jszip/jszip.min.js"></script>
	<!-- PLUGIN -->
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/global/sweetalert/sweetalert2.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/global/alphanum/jquery.alphanum.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/global/jquery-validation/dist/jquery.validate.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/select2/dist/js/select2.full.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/moment/moment.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-datepicker/bs-datepicker.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-daterangepicker/daterangepicker.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-wysihtml5/bs-wysihtml5.all.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/bs-timepicker/bs-timepicker.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/jquery-slimscroll/jquery.slimscroll.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/fastclick/fastclick.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/pace/pace.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/toastr/toastr.min.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/input-mask/jquery.inputmask.js"></script>
	<script type="text/javascript" src="<?=siteURL()?>bssmitlab/_assets/portalz/input-mask/jquery.inputmask.date.extensions.js"></script>

